spring.application.name=cafe-management-web
server.port=${PORT:8080}
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
app.upload.product-images-dir=${PRODUCT_IMAGE_UPLOAD_DIR:uploads/products}
app.weather.api-url=${WEATHER_API_URL:https://api.open-meteo.com/v1/forecast}
app.weather.latitude=${WEATHER_LATITUDE:10.7769}
app.weather.longitude=${WEATHER_LONGITUDE:106.7009}
app.weather.location-name=${WEATHER_LOCATION_NAME:TP. Ho Chi Minh}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:gg.tms205@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wbsb zhum oebu cawp}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
app.mail.from=${MAIL_FROM:${MAIL_USERNAME:gg.tms205@gmail.com}}
