USE master;
GO

IF DB_ID(N'CAFEMANAGEMENT') IS NULL
BEGIN
    CREATE DATABASE CAFEMANAGEMENT;
END;
GO

ALTER DATABASE CAFEMANAGEMENT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE CAFEMANAGEMENT SET MULTI_USER;
GO

USE CAFEMANAGEMENT;
GO

DROP TRIGGER IF EXISTS trg_UpdateOrderTotal;
DROP TRIGGER IF EXISTS trg_PreventAddToPaidOrder;
DROP TRIGGER IF EXISTS trg_UpdateTableStatusOnInsert;
DROP TRIGGER IF EXISTS trg_UpdateTableStatusOnUpdate;
GO

DROP PROCEDURE IF EXISTS sp_AddSampleData;
DROP PROCEDURE IF EXISTS sp_CreateOrder;
DROP PROCEDURE IF EXISTS sp_AddProductToOrder;
DROP PROCEDURE IF EXISTS sp_PayOrder;
DROP PROCEDURE IF EXISTS sp_GetDailyRevenueReport;
DROP PROCEDURE IF EXISTS sp_RegisterStaff;
DROP PROCEDURE IF EXISTS sp_RegisterCustomer;
DROP PROCEDURE IF EXISTS sp_LoginStaff;
DROP PROCEDURE IF EXISTS sp_LoginCustomer;
GO

DROP FUNCTION IF EXISTS fn_GetRevenueByDate;
GO

DROP TABLE IF EXISTS UserLog;
DROP TABLE IF EXISTS Delivery;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS OrderDetail;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS TableCafe;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS [User];
GO

CREATE TABLE [User] (
    user_id INT IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin','staff')),
    full_name NVARCHAR(100),
    -- Recovery OTP is sent to this email for admin/staff accounts.
    email VARCHAR(100),
    is_active BIT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Customer (
    customer_id INT IDENTITY PRIMARY KEY,
    phone VARCHAR(15) NOT NULL UNIQUE,
    -- BCrypt hashes generated by the application are stored in this column.
    password VARCHAR(255) NOT NULL,
    full_name NVARCHAR(100) NOT NULL,
    email VARCHAR(100),
    address NVARCHAR(200),
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    total_spent DECIMAL(12,2) NOT NULL DEFAULT 0,
    is_active BIT NOT NULL DEFAULT 1
);

CREATE TABLE CustomerFeedback (
    feedback_id INT IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    reason NVARCHAR(500) NOT NULL,
    expectation NVARCHAR(1000) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_CustomerFeedback_Customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

CREATE TABLE TableCafe (
    table_id INT IDENTITY PRIMARY KEY,
    table_name NVARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'empty'
        CHECK (status IN ('empty','occupied'))
);

CREATE TABLE Category (
    category_id INT IDENTITY PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Product (
    product_id INT IDENTITY PRIMARY KEY,
    name NVARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    category_id INT NOT NULL,
    is_available BIT NOT NULL DEFAULT 1,
    image_url VARCHAR(500) NULL,
    image_name NVARCHAR(200) NULL,
    CONSTRAINT UQ_Product UNIQUE (name, category_id),
    CONSTRAINT FK_Product_Category FOREIGN KEY (category_id) REFERENCES Category(category_id)
);

CREATE TABLE Orders (
    order_id INT IDENTITY PRIMARY KEY,
    table_id INT NULL,
    user_id INT NULL,
    customer_id INT NULL,
    order_time DATETIME NOT NULL DEFAULT GETDATE(),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','paid','cancelled')),
    total DECIMAL(12,2) NOT NULL DEFAULT 0,
    order_type VARCHAR(20) NOT NULL DEFAULT 'at_shop'
        CHECK (order_type IN ('at_shop','delivery','takeaway')),
    delivery_address NVARCHAR(200) NULL,
    customer_note NVARCHAR(500) NULL,
    requested_payment_method VARCHAR(20) NULL
        CHECK (requested_payment_method IS NULL OR requested_payment_method IN ('cash','momo','bank')),
    CONSTRAINT FK_Orders_TableCafe FOREIGN KEY (table_id) REFERENCES TableCafe(table_id),
    CONSTRAINT FK_Orders_User FOREIGN KEY (user_id) REFERENCES [User](user_id),
    CONSTRAINT FK_Orders_Customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

CREATE TABLE OrderDetail (
    order_detail_id INT IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    CONSTRAINT UQ_Order_Product UNIQUE (order_id, product_id),
    CONSTRAINT FK_OrderDetail_Orders FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE,
    CONSTRAINT FK_OrderDetail_Product FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

CREATE TABLE Cart (
    cart_id INT IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Cart_Customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id),
    CONSTRAINT FK_Cart_Product FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

CREATE TABLE Payment (
    payment_id INT IDENTITY PRIMARY KEY,
    order_id INT NOT NULL UNIQUE,
    payment_time DATETIME NOT NULL DEFAULT GETDATE(),
    method VARCHAR(50) NOT NULL CHECK (method IN ('cash','momo','bank')),
    amount_paid DECIMAL(12,2) NOT NULL,
    CONSTRAINT FK_Payment_Orders FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

CREATE TABLE Delivery (
    delivery_id INT IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    shipper_name NVARCHAR(100),
    shipper_phone VARCHAR(15),
    delivery_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (delivery_status IN ('pending','shipping','delivered','cancelled')),
    delivery_time DATETIME,
    shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Delivery_Orders FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

CREATE TABLE UserLog (
    log_id INT IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    login_time DATETIME NOT NULL DEFAULT GETDATE(),
    ip_address VARCHAR(50),
    CONSTRAINT FK_UserLog_User FOREIGN KEY (user_id) REFERENCES [User](user_id)
);

CREATE INDEX idx_product_category ON Product(category_id);
CREATE INDEX idx_order_user ON Orders(user_id);
CREATE INDEX idx_order_table ON Orders(table_id);
CREATE INDEX idx_order_status ON Orders(status);
CREATE INDEX idx_orderdetail_order ON OrderDetail(order_id);
CREATE INDEX idx_payment_order ON Payment(order_id);
GO

CREATE TRIGGER trg_UpdateOrderTotal
ON OrderDetail
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE o
    SET total = (
        SELECT ISNULL(SUM(od.quantity * od.price), 0)
        FROM OrderDetail od
        WHERE od.order_id = o.order_id
    )
    FROM Orders o
    WHERE o.order_id IN (
        SELECT order_id FROM inserted
        UNION
        SELECT order_id FROM deleted
    );
END;
GO

CREATE TRIGGER trg_PreventAddToPaidOrder
ON OrderDetail
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN Orders o ON i.order_id = o.order_id
        WHERE o.status = 'paid'
    )
    BEGIN
        RAISERROR(N'Không thể thêm hoặc sửa món trong đơn hàng đã thanh toán', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER trg_UpdateTableStatusOnInsert
ON Orders
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE t
    SET status = 'occupied'
    FROM TableCafe t
    JOIN inserted i ON t.table_id = i.table_id
    WHERE i.status = 'pending'
      AND i.table_id IS NOT NULL;
END;
GO

CREATE TRIGGER trg_UpdateTableStatusOnUpdate
ON Orders
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF UPDATE(status)
    BEGIN
        UPDATE t
        SET status = CASE WHEN i.status = 'paid' THEN 'empty' ELSE 'occupied' END
        FROM TableCafe t
        JOIN inserted i ON t.table_id = i.table_id
        JOIN deleted d ON i.order_id = d.order_id
        WHERE i.status <> d.status
          AND i.table_id IS NOT NULL;
    END
END;
GO

CREATE PROCEDURE sp_CreateOrder
    @table_id INT,
    @user_id INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TableCafe WHERE table_id = @table_id AND status = 'occupied')
    BEGIN
        RAISERROR(N'Bàn đang có người, không thể tạo đơn mới', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM [User] WHERE user_id = @user_id AND is_active = 1)
    BEGIN
        RAISERROR(N'Nhân viên không tồn tại hoặc đã bị vô hiệu', 16, 1);
        RETURN;
    END;

    INSERT INTO Orders(table_id, user_id)
    VALUES(@table_id, @user_id);

    SELECT CONVERT(INT, SCOPE_IDENTITY()) AS order_id;
END;
GO

CREATE PROCEDURE sp_AddProductToOrder
    @order_id INT,
    @product_id INT,
    @quantity INT
AS
BEGIN
    SET NOCOUNT ON;

    IF @quantity <= 0
    BEGIN
        RAISERROR(N'Số lượng phải lớn hơn 0', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM Orders WHERE order_id = @order_id)
    BEGIN
        RAISERROR(N'Đơn hàng không tồn tại', 16, 1);
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM Orders WHERE order_id = @order_id AND status = 'paid')
    BEGIN
        RAISERROR(N'Đơn hàng đã thanh toán, không thể thêm món', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM Product WHERE product_id = @product_id AND is_available = 1)
    BEGIN
        RAISERROR(N'Sản phẩm không tồn tại hoặc đã ngừng bán', 16, 1);
        RETURN;
    END;

    DECLARE @price DECIMAL(10,2);
    SELECT @price = price FROM Product WHERE product_id = @product_id;

    IF EXISTS (SELECT 1 FROM OrderDetail WHERE order_id = @order_id AND product_id = @product_id)
    BEGIN
        UPDATE OrderDetail
        SET quantity = quantity + @quantity
        WHERE order_id = @order_id AND product_id = @product_id;
    END
    ELSE
    BEGIN
        INSERT INTO OrderDetail(order_id, product_id, quantity, price)
        VALUES(@order_id, @product_id, @quantity, @price);
    END;
END;
GO

CREATE PROCEDURE sp_PayOrder
    @order_id INT,
    @method VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    IF @method NOT IN ('cash','momo','bank')
    BEGIN
        RAISERROR(N'Phương thức thanh toán không hợp lệ', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM Orders WHERE order_id = @order_id AND status = 'pending')
    BEGIN
        RAISERROR(N'Đơn hàng không tồn tại hoặc đã được thanh toán', 16, 1);
        RETURN;
    END;

    DECLARE @total DECIMAL(12,2);
    SELECT @total = total FROM Orders WHERE order_id = @order_id;

    IF @total <= 0
    BEGIN
        RAISERROR(N'Đơn hàng chưa có món', 16, 1);
        RETURN;
    END;

    UPDATE Orders
    SET status = 'paid'
    WHERE order_id = @order_id;

    INSERT INTO Payment(order_id, method, amount_paid)
    VALUES(@order_id, @method, @total);
END;
GO

CREATE PROCEDURE sp_GetDailyRevenueReport
    @date DATE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        @date AS report_date,
        COUNT(DISTINCT o.order_id) AS total_orders,
        ISNULL(SUM(o.total), 0) AS total_revenue,
        COUNT(DISTINCT CASE WHEN p.method = 'cash' THEN p.order_id END) AS cash_orders,
        COUNT(DISTINCT CASE WHEN p.method = 'momo' THEN p.order_id END) AS momo_orders,
        COUNT(DISTINCT CASE WHEN p.method = 'bank' THEN p.order_id END) AS bank_orders
    FROM Orders o
    LEFT JOIN Payment p ON o.order_id = p.order_id
    WHERE CAST(o.order_time AS DATE) = @date
      AND o.status = 'paid';
END;
GO

CREATE FUNCTION fn_GetRevenueByDate(@date DATE)
RETURNS DECIMAL(12,2)
AS
BEGIN
    DECLARE @total DECIMAL(12,2);

    SELECT @total = SUM(total)
    FROM Orders
    WHERE CAST(order_time AS DATE) = @date
      AND status = 'paid';

    RETURN ISNULL(@total, 0);
END;
GO

CREATE PROCEDURE sp_RegisterStaff
    @username VARCHAR(50),
    @password VARCHAR(255),
    @full_name NVARCHAR(100),
    @email VARCHAR(100),
    @role VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF @role NOT IN ('admin','staff')
    BEGIN
        RAISERROR(N'Vai trò không hợp lệ', 16, 1);
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM [User] WHERE username = @username)
    BEGIN
        RAISERROR(N'Tên đăng nhập đã tồn tại', 16, 1);
        RETURN;
    END;

    INSERT INTO [User] (username, password, role, full_name, email, is_active)
    VALUES (@username, @password, @role, @full_name, @email, 1);

    SELECT CONVERT(INT, SCOPE_IDENTITY()) AS user_id;
END;
GO

CREATE PROCEDURE sp_RegisterCustomer
    @phone VARCHAR(15),
    @password VARCHAR(255),
    @full_name NVARCHAR(100),
    @email VARCHAR(100),
    @address NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM Customer WHERE phone = @phone)
    BEGIN
        RAISERROR(N'Số điện thoại đã được đăng ký', 16, 1);
        RETURN;
    END;

    INSERT INTO Customer (phone, password, full_name, email, address)
    VALUES (@phone, @password, @full_name, @email, @address);

    SELECT CONVERT(INT, SCOPE_IDENTITY()) AS customer_id;
END;
GO

CREATE PROCEDURE sp_LoginStaff
    @username VARCHAR(50),
    @password VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT user_id, username, role, full_name, is_active
    FROM [User]
    WHERE username = @username
      AND password = @password
      AND is_active = 1;
END;
GO

-- Customer password authentication is performed in Java with BCrypt.
-- This legacy procedure does not verify BCrypt hashes and is not used by the application.
CREATE PROCEDURE sp_LoginCustomer
    @phone VARCHAR(15),
    @password VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT customer_id, phone, full_name, email, address, total_spent, is_active
    FROM Customer
    WHERE phone = @phone
      AND password = @password
      AND is_active = 1;
END;
GO

CREATE PROCEDURE sp_AddSampleData
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM UserLog;
    DELETE FROM Delivery;
    DELETE FROM Payment;
    DELETE FROM Cart;
    DELETE FROM OrderDetail;
    DELETE FROM Orders;
    DELETE FROM Product;
    DELETE FROM Category;
    DELETE FROM TableCafe;
    DELETE FROM Customer;
    DELETE FROM [User];

    DBCC CHECKIDENT ('UserLog', RESEED, 1);
    DBCC CHECKIDENT ('Delivery', RESEED, 1);
    DBCC CHECKIDENT ('Payment', RESEED, 1);
    DBCC CHECKIDENT ('Cart', RESEED, 1);
    DBCC CHECKIDENT ('OrderDetail', RESEED, 1);
    DBCC CHECKIDENT ('Orders', RESEED, 1);
    DBCC CHECKIDENT ('Product', RESEED, 1);
    DBCC CHECKIDENT ('Category', RESEED, 1);
    DBCC CHECKIDENT ('TableCafe', RESEED, 1);
    DBCC CHECKIDENT ('Customer', RESEED, 1);
    DBCC CHECKIDENT ('[User]', RESEED, 1);

    -- Add real Gmail addresses from the admin screen or update them below.
    -- Do not use example addresses when testing password recovery.
    INSERT INTO [User] (username, password, role, full_name, email, is_active) VALUES
    ('admin', 'admin123', 'admin', N'Quản trị viên', NULL, 1),
    ('staff1', 'staff123', 'staff', N'Nguyễn Văn An', NULL, 1),
    ('staff2', 'staff123', 'staff', N'Trần Thị Bình', NULL, 1),
    ('staff3', 'staff123', 'staff', N'Lê Văn Cường', NULL, 1);

    INSERT INTO TableCafe (table_name, status) VALUES
    (N'Bàn 1', 'empty'), (N'Bàn 2', 'empty'), (N'Bàn 3', 'empty'), (N'Bàn 4', 'empty'), (N'Bàn 5', 'empty'),
    (N'Bàn 6', 'empty'), (N'Bàn 7', 'empty'), (N'Bàn 8', 'empty'), (N'Bàn 9', 'empty'), (N'Bàn 10', 'empty'),
    (N'Bàn VIP 1', 'empty'), (N'Bàn VIP 2', 'empty'), (N'Bàn ngoài trời 1', 'empty'), (N'Bàn ngoài trời 2', 'empty');

    INSERT INTO Category (name) VALUES
    (N'Cà phê'),
    (N'Trà các loại'),
    (N'Nước ép & Sinh tố'),
    (N'Bánh ngọt & Bánh mì'),
    (N'Ăn vặt & Món mặn'),
    (N'Kem & Tráng miệng'),
    (N'Đồ uống khác'),
    (N'Đá xay & Smoothie');

    INSERT INTO Product (name, price, category_id, is_available, image_url, image_name) VALUES
    (N'Cà phê đen nóng', 25000, 1, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Cà phê đen đá', 27000, 1, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Cà phê sữa đá', 32000, 1, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Bạc xỉu', 35000, 1, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Cappuccino', 45000, 1, 1, '/images/products/latte.jpg', 'latte.jpg'),
    (N'Latte', 45000, 1, 1, '/images/products/latte.jpg', 'latte.jpg'),
    (N'Espresso đơn', 25000, 1, 1, '/images/products/espresso.jpg', 'espresso.jpg'),
    (N'Americano', 40000, 1, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Trà đào cam sả', 45000, 2, 1, '/images/products/tea.jpg', 'tea.jpg'),
    (N'Trà vải', 42000, 2, 1, '/images/products/tea.jpg', 'tea.jpg'),
    (N'Trà sữa trân châu', 50000, 2, 1, '/images/products/milk-tea.jpg', 'milk-tea.jpg'),
    (N'Trà sữa matcha', 55000, 2, 1, '/images/products/milk-tea.jpg', 'milk-tea.jpg'),
    (N'Nước ép cam', 45000, 3, 1, '/images/products/juice.jpg', 'juice.jpg'),
    (N'Nước ép dưa hấu', 40000, 3, 1, '/images/products/juice.jpg', 'juice.jpg'),
    (N'Sinh tố bơ', 55000, 3, 1, '/images/products/smoothie.jpg', 'smoothie.jpg'),
    (N'Sinh tố xoài', 50000, 3, 1, '/images/products/smoothie.jpg', 'smoothie.jpg'),
    (N'Bánh mì bơ tỏi', 35000, 4, 1, '/images/products/sandwich.jpg', 'sandwich.jpg'),
    (N'Croissant', 35000, 4, 1, '/images/products/cake.jpg', 'cake.jpg'),
    (N'Bánh tiramisu', 50000, 4, 1, '/images/products/cake.jpg', 'cake.jpg'),
    (N'Bánh brownie', 35000, 4, 1, '/images/products/cake.jpg', 'cake.jpg'),
    (N'Khoai tây chiên', 35000, 5, 1, '/images/products/sandwich.jpg', 'sandwich.jpg'),
    (N'Sandwich gà', 45000, 5, 1, '/images/products/sandwich.jpg', 'sandwich.jpg'),
    (N'Sandwich bò', 50000, 5, 1, '/images/products/sandwich.jpg', 'sandwich.jpg'),
    (N'Kem vani', 20000, 6, 1, '/images/products/default.jpg', 'default.jpg'),
    (N'Kem socola', 20000, 6, 1, '/images/products/default.jpg', 'default.jpg'),
    (N'Sữa tươi matcha', 40000, 7, 1, '/images/products/milk-tea.jpg', 'milk-tea.jpg'),
    (N'Cacao nóng', 35000, 7, 1, '/images/products/default.jpg', 'default.jpg'),
    (N'Soda chanh', 30000, 7, 1, '/images/products/juice.jpg', 'juice.jpg'),
    (N'Đá xay cà phê', 45000, 8, 1, '/images/products/coffee.jpg', 'coffee.jpg'),
    (N'Đá xay socola', 50000, 8, 1, '/images/products/smoothie.jpg', 'smoothie.jpg'),
    (N'Matcha latte', 55000, 8, 1, '/images/products/latte.jpg', 'latte.jpg');

    -- Password for seeded customer accounts is 123456, stored as a BCrypt hash.
    INSERT INTO Customer (phone, password, full_name, email, address, total_spent) VALUES
    ('0987654321', '$2a$10$mzIScSoaFEmgRRCWLsPTnOQq.TwAehFkm1/wJDHqWCjKANvMOYWA6', N'Trần Văn Bình', 'binh.tran@email.com', N'12 Nguyễn Huệ, Q1', 0),
    ('0978123456', '$2a$10$mzIScSoaFEmgRRCWLsPTnOQq.TwAehFkm1/wJDHqWCjKANvMOYWA6', N'Lê Thị Cúc', 'cuc.le@email.com', N'45 Lê Lợi, Q3', 0),
    ('0968234567', '$2a$10$mzIScSoaFEmgRRCWLsPTnOQq.TwAehFkm1/wJDHqWCjKANvMOYWA6', N'Phạm Văn Đức', 'duc.pham@email.com', N'78 Phạm Ngũ Lão, Q5', 0);

    DECLARE @orderId INT;

    INSERT INTO Orders(table_id, user_id) VALUES (1, 2);
    SET @orderId = SCOPE_IDENTITY();
    EXEC sp_AddProductToOrder @orderId, 1, 2;
    EXEC sp_AddProductToOrder @orderId, 9, 1;
    EXEC sp_PayOrder @orderId, 'cash';

    INSERT INTO Orders(table_id, user_id) VALUES (2, 3);
    SET @orderId = SCOPE_IDENTITY();
    EXEC sp_AddProductToOrder @orderId, 6, 1;
    EXEC sp_AddProductToOrder @orderId, 18, 1;
    EXEC sp_PayOrder @orderId, 'momo';

    INSERT INTO Orders(table_id, user_id) VALUES (3, 2);
    SET @orderId = SCOPE_IDENTITY();
    EXEC sp_AddProductToOrder @orderId, 11, 2;
    EXEC sp_AddProductToOrder @orderId, 22, 1;
    EXEC sp_PayOrder @orderId, 'bank';

    INSERT INTO Orders(customer_id, order_type, customer_note, requested_payment_method)
    VALUES (1, 'takeaway', N'Ít đá, nhận tại quầy', 'momo');
    SET @orderId = SCOPE_IDENTITY();
    EXEC sp_AddProductToOrder @orderId, 4, 1;
    EXEC sp_AddProductToOrder @orderId, 11, 2;

    PRINT N'Dữ liệu mẫu đã được thêm thành công.';
END;
GO

EXEC sp_AddSampleData;
GO



IF OBJECT_ID(N'dbo.User', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.User', N'email') IS NULL
BEGIN
    ALTER TABLE dbo.[User] ADD email VARCHAR(100) NULL;
END;
GO

IF OBJECT_ID(N'dbo.User', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.User', N'is_deleted') IS NULL
BEGIN
    ALTER TABLE dbo.[User]
        ADD is_deleted BIT NOT NULL CONSTRAINT DF_User_is_deleted DEFAULT 0;
END;
GO

/* Customer registration, BCrypt passwords and password recovery. */
IF OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'password') IS NULL
BEGIN
    ALTER TABLE dbo.Customer ADD password VARCHAR(255) NULL;

    -- Existing accounts receive a temporary BCrypt password: 123456.
    -- Require customers to change it after the first login.
    UPDATE dbo.Customer
    SET password = '$2a$10$mzIScSoaFEmgRRCWLsPTnOQq.TwAehFkm1/wJDHqWCjKANvMOYWA6'
    WHERE password IS NULL;

    ALTER TABLE dbo.Customer ALTER COLUMN password VARCHAR(255) NOT NULL;
END;
GO

IF OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'password') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'password') < 60
BEGIN
    ALTER TABLE dbo.Customer ALTER COLUMN password VARCHAR(255) NOT NULL;
END;
GO

IF OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'email') IS NULL
BEGIN
    ALTER TABLE dbo.Customer ADD email VARCHAR(100) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'is_active') IS NULL
BEGIN
    ALTER TABLE dbo.Customer
        ADD is_active BIT NOT NULL CONSTRAINT DF_Customer_is_active DEFAULT 1;
END;
GO

IF OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Customer', N'is_deleted') IS NULL
BEGIN
    ALTER TABLE dbo.Customer
        ADD is_deleted BIT NOT NULL CONSTRAINT DF_Customer_is_deleted DEFAULT 0;
END;
GO

/* Product image upload support. */
IF OBJECT_ID(N'dbo.Product', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Product', N'image_url') IS NULL
BEGIN
    ALTER TABLE dbo.Product ADD image_url VARCHAR(500) NULL;
END;
GO

/* Customer checkout and submitted-order realtime support. */
IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'customer_id') IS NULL
BEGIN
    ALTER TABLE dbo.Orders ADD customer_id INT NULL;
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.Customer', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'customer_id') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1
       FROM sys.foreign_keys
       WHERE parent_object_id = OBJECT_ID(N'dbo.Orders')
         AND referenced_object_id = OBJECT_ID(N'dbo.Customer')
   )
BEGIN
    ALTER TABLE dbo.Orders WITH CHECK
        ADD CONSTRAINT FK_Orders_Customer
        FOREIGN KEY (customer_id) REFERENCES dbo.Customer(customer_id);
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'order_type') IS NULL
BEGIN
    ALTER TABLE dbo.Orders
        ADD order_type VARCHAR(20) NOT NULL
            CONSTRAINT DF_Orders_order_type DEFAULT 'takeaway';
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'delivery_address') IS NULL
BEGIN
    ALTER TABLE dbo.Orders ADD delivery_address NVARCHAR(200) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'customer_note') IS NULL
BEGIN
    ALTER TABLE dbo.Orders ADD customer_note NVARCHAR(500) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'requested_payment_method') IS NULL
BEGIN
    ALTER TABLE dbo.Orders ADD requested_payment_method VARCHAR(20) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.Orders', N'is_deleted') IS NULL
BEGIN
    ALTER TABLE dbo.Orders
        ADD is_deleted BIT NOT NULL CONSTRAINT DF_Orders_is_deleted DEFAULT 0;
END;
GO

/* Cancelled orders are used by the admin order-management screen. */
IF OBJECT_ID(N'dbo.Orders', N'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1
       FROM sys.check_constraints
       WHERE parent_object_id = OBJECT_ID(N'dbo.Orders')
         AND definition LIKE '%status%'
         AND definition LIKE '%cancelled%'
   )
BEGIN
    DECLARE @statusConstraint SYSNAME;
    SELECT TOP (1) @statusConstraint = name
    FROM sys.check_constraints
    WHERE parent_object_id = OBJECT_ID(N'dbo.Orders')
      AND definition LIKE '%status%';

    IF @statusConstraint IS NOT NULL
    BEGIN
        EXEC (N'ALTER TABLE dbo.Orders DROP CONSTRAINT [' + @statusConstraint + N']');
    END;

    ALTER TABLE dbo.Orders WITH CHECK
        ADD CONSTRAINT CK_Orders_status
        CHECK (status IN ('pending', 'paid', 'cancelled'));
END;
GO

/*
  Replace NULL below with real Gmail addresses, for example:
  DECLARE @adminEmail VARCHAR(100) = 'admin.real@gmail.com';
  OTP is sent only when username and the entered email match this value.
*/
DECLARE @adminEmail VARCHAR(100) = NULL;
DECLARE @staff1Email VARCHAR(100) = NULL;
DECLARE @staff2Email VARCHAR(100) = NULL;
DECLARE @staff3Email VARCHAR(100) = NULL;

IF @adminEmail IS NOT NULL
    UPDATE dbo.[User] SET email = @adminEmail WHERE username = 'admin';
IF @staff1Email IS NOT NULL
    UPDATE dbo.[User] SET email = @staff1Email WHERE username = 'staff1';
IF @staff2Email IS NOT NULL
    UPDATE dbo.[User] SET email = @staff2Email WHERE username = 'staff2';
IF @staff3Email IS NOT NULL
    UPDATE dbo.[User] SET email = @staff3Email WHERE username = 'staff3';

SELECT username, full_name, role, email, is_active
FROM dbo.[User]
WHERE role IN ('admin', 'staff')
ORDER BY user_id;
GO

/*
  AFTER RESET: configure real recovery Gmail addresses for internal accounts,
  or enter them on the Admin > Nhân viên page.

  UPDATE dbo.[User] SET email = 'admin.real@gmail.com'  WHERE username = 'admin';
  UPDATE dbo.[User] SET email = 'staff1.real@gmail.com' WHERE username = 'staff1';
  UPDATE dbo.[User] SET email = 'staff2.real@gmail.com' WHERE username = 'staff2';
  UPDATE dbo.[User] SET email = 'staff3.real@gmail.com' WHERE username = 'staff3';
*/
